apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-deploy
  name: nodejs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-deploy
  template:
    metadata:
      labels:
        app: nodejs-deploy
    spec:
      containers:
      - image: emrverskn/nodejs-image
        name: nodejs
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: postgres-secret
        resources: {}