apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-service
  name: nodejs-service
spec:
  selector:
    app: nodejs-deploy
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30002
  type: NodePort