apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-service
  name: react-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: react-deploy
  type: NodePort